version: "3.7"

networks:
    lempnet:

volumes:
    db_data:
        external: true

services:
    # sass-server:
    #     image: node:10
    #     container_name: sass-server
    #     user: node
    #     working_dir: "/sass-server"
    #     ports:
    #         - "3003:3003"
    #     volumes:
    #         - ./:/sass-server
    #     networks:
    #         - lempnet
    #     command: "npx pm2 start ecosystem.config.js --no-daemon"

    # apache:
    #     image: httpd:latest
    #     container_name: apache
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - ./www/:/var/www/html/
    #         - ./config/apache/default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    #     networks:
    #         - lempnet

    # mqtt:
    #     container_name: mqtt
    #     image: eclipse-mosquitto
    #     restart: always
    #     volumes:
    #         - ./config/mosquitto/config:/mosquitto/config
    #         - ./config/mosquitto/data:/mosquitto/data
    #         - ./config/mosquitto/log:/mosquitto/log
    #     ports:
    #         - 1883:1883
    #         - 9001:9001
    #     networks:
    #         - lempnet

    web:
        image: nginx:latest
        container_name: web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html:cached
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        networks:
            - lempnet

    php:
        image: php7.3
        container_name: php
        ports:
            - "9080:9000"
        volumes:
            - ./www:/var/www/html:cached
            - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
        networks:
            - lempnet

    mysql:
        image: mysql:5.7
        container_name: mysql
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - lempnet

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - lempnet
