web:
    image: nginx:latest
    container_name: web
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./www:/var/www/html
        - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
    links:
        - php
        
php:
    image: phillaf/php-mysql
    container_name: php
    ports:
        - "9080:9000"
    volumes:
        - ./www:/var/www/html
        - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
        - mysql
        - redis

mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
        - db_data:/var/lib/mysql
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: password

redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"